spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: wineadmin
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false
   
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher